### ISSUE TITLE
Experiment stack None not found & Unable to connect to tracker

### ISSUE THREAD

**Issue by MinyueDayuan** [votchallenge/toolkit#113]
it seems i can only initialize environment for vot 2013,2014,2017,vots2023,but fail for 2015,2016,...etc.
And i can not connect tracker,i don't know why?
![Screenshot from 2023-11-29 19-57-53](https://github.com/votchallenge/toolkit/assets/70747916/fb8efd3e-3096-45a8-af4b-ae709b53d78d)
![Screenshot from 2023-11-29 20-01-47](https://github.com/votchallenge/toolkit/assets/70747916/4466c346-5308-4c47-af49-fc973681f11c)
![Screenshot from 2023-11-29 20-02-15](https://github.com/votchallenge/toolkit/assets/70747916/4c6f4df6-b0ac-49a6-9c12-5da91de5d211)

**Comment by 858949416** [comment]
请问你解决了上述问题（Experiment stack None not found）嘛？
May I ask if you have resolved the above issue (Experiment stack None not found)?

**Comment by 858949416** [comment]
May I ask if you have resolved the above issue (Experiment stack None not found)?

**Comment by lukacu** [comment]
Well, the stacks were reorganized a bit since we had a mess with subchallenges recently. So, for vot2015, you must use  "vot2015/rgb" as a stack name. You can get the name of stacks if you run "vot initialize" (without a stack). I hope this answers your question, and I am sorry for the delay (I had some busy months recently).
